// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading_progress.sql

package sqlc

import (
	"context"
)

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT id, user_id, article_path, article_title, progress_percent, scroll_y, finished, last_read_at, created_at, updated_at
FROM reading_progress
WHERE user_id = $1 AND article_path = $2
`

type GetReadingProgressParams struct {
	UserID      int64
	ArticlePath string
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, getReadingProgress, arg.UserID, arg.ArticlePath)
	var i ReadingProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArticlePath,
		&i.ArticleTitle,
		&i.ProgressPercent,
		&i.ScrollY,
		&i.Finished,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecentReadingProgress = `-- name: ListRecentReadingProgress :many
SELECT id, user_id, article_path, article_title, progress_percent, scroll_y, finished, last_read_at, created_at, updated_at
FROM reading_progress
WHERE user_id = $1
ORDER BY last_read_at DESC
LIMIT $2
`

type ListRecentReadingProgressParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) ListRecentReadingProgress(ctx context.Context, arg ListRecentReadingProgressParams) ([]ReadingProgress, error) {
	rows, err := q.db.Query(ctx, listRecentReadingProgress, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadingProgress
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ArticlePath,
			&i.ArticleTitle,
			&i.ProgressPercent,
			&i.ScrollY,
			&i.Finished,
			&i.LastReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :one
INSERT INTO reading_progress (user_id, article_path, article_title, progress_percent, scroll_y, finished, last_read_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (user_id, article_path)
DO UPDATE SET
    article_title = EXCLUDED.article_title,
    progress_percent = EXCLUDED.progress_percent,
    scroll_y = EXCLUDED.scroll_y,
    finished = EXCLUDED.finished,
    last_read_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, article_path, article_title, progress_percent, scroll_y, finished, last_read_at, created_at, updated_at
`

type UpsertReadingProgressParams struct {
	UserID          int64
	ArticlePath     string
	ArticleTitle    string
	ProgressPercent int32
	ScrollY         int32
	Finished        bool
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, upsertReadingProgress,
		arg.UserID,
		arg.ArticlePath,
		arg.ArticleTitle,
		arg.ProgressPercent,
		arg.ScrollY,
		arg.Finished,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArticlePath,
		&i.ArticleTitle,
		&i.ProgressPercent,
		&i.ScrollY,
		&i.Finished,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
