// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading_progress.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCourseProgressForCourses = `-- name: CreateCourseProgressForCourses :exec
WITH affected_user_courses AS (
    SELECT DISTINCT reading_progress.user_id, course_articles.course_id
    FROM course_articles
    JOIN content_items ON content_items.id = course_articles.content_item_id
    JOIN reading_progress ON reading_progress.article_path = content_items.public_path
    WHERE course_articles.course_id = ANY($1::bigint[])
      AND course_articles.is_active
      AND content_items.is_active
), course_metrics AS (
    SELECT
        affected_user_courses.user_id,
        affected_user_courses.course_id,
        COUNT(reading_progress.id)::int AS learned_article_count,
        ROUND(AVG(COALESCE(reading_progress.progress_percent, 0)))::int AS average_progress_percent
    FROM affected_user_courses
    JOIN course_articles ON course_articles.course_id = affected_user_courses.course_id AND course_articles.is_active
    JOIN content_items ON content_items.id = course_articles.content_item_id AND content_items.is_active
    LEFT JOIN reading_progress
      ON reading_progress.user_id = affected_user_courses.user_id
     AND reading_progress.article_path = content_items.public_path
    GROUP BY affected_user_courses.user_id, affected_user_courses.course_id
)
INSERT INTO user_course_progress (
    user_id, course_id, learned_article_count, average_progress_percent, latest_content_item_id, latest_read_at, updated_at
)
SELECT
    course_metrics.user_id,
    course_metrics.course_id,
    course_metrics.learned_article_count,
    course_metrics.average_progress_percent,
    latest.content_item_id,
    latest.last_read_at,
    NOW()
FROM course_metrics
LEFT JOIN LATERAL (
    SELECT course_articles.content_item_id, reading_progress.last_read_at
    FROM course_articles
    JOIN content_items ON content_items.id = course_articles.content_item_id
    JOIN reading_progress
      ON reading_progress.article_path = content_items.public_path
     AND reading_progress.user_id = course_metrics.user_id
    WHERE course_articles.course_id = course_metrics.course_id
      AND course_articles.is_active
      AND content_items.is_active
    ORDER BY reading_progress.last_read_at DESC, reading_progress.id DESC
    LIMIT 1
) AS latest ON TRUE
`

func (q *Queries) CreateCourseProgressForCourses(ctx context.Context, courseIds []int64) error {
	_, err := q.db.Exec(ctx, createCourseProgressForCourses, courseIds)
	return err
}

const getActiveContentItem = `-- name: GetActiveContentItem :one
SELECT id, public_path, title, content_type
FROM content_items
WHERE public_path = $1
  AND is_active
  AND content_type IN ('course_article', 'article', 'geektime_article', 'love_course_article')
`

type GetActiveContentItemRow struct {
	ID          int64
	PublicPath  string
	Title       string
	ContentType string
}

func (q *Queries) GetActiveContentItem(ctx context.Context, publicPath string) (GetActiveContentItemRow, error) {
	row := q.db.QueryRow(ctx, getActiveContentItem, publicPath)
	var i GetActiveContentItemRow
	err := row.Scan(
		&i.ID,
		&i.PublicPath,
		&i.Title,
		&i.ContentType,
	)
	return i, err
}

const getCourseSummary = `-- name: GetCourseSummary :one
SELECT courses.id, courses.public_path, courses.title, courses.article_count,
       COALESCE(user_course_progress.learned_article_count, 0)::int AS learned_article_count,
       COALESCE(user_course_progress.average_progress_percent, 0)::int AS average_progress_percent,
       user_course_progress.latest_read_at
FROM courses
LEFT JOIN user_course_progress
  ON user_course_progress.course_id = courses.id
 AND user_course_progress.user_id = $1
WHERE courses.public_path = $2
  AND courses.is_active
`

type GetCourseSummaryParams struct {
	UserID     int64
	PublicPath string
}

type GetCourseSummaryRow struct {
	ID                     int64
	PublicPath             string
	Title                  string
	ArticleCount           int32
	LearnedArticleCount    int32
	AverageProgressPercent int32
	LatestReadAt           pgtype.Timestamptz
}

func (q *Queries) GetCourseSummary(ctx context.Context, arg GetCourseSummaryParams) (GetCourseSummaryRow, error) {
	row := q.db.QueryRow(ctx, getCourseSummary, arg.UserID, arg.PublicPath)
	var i GetCourseSummaryRow
	err := row.Scan(
		&i.ID,
		&i.PublicPath,
		&i.Title,
		&i.ArticleCount,
		&i.LearnedArticleCount,
		&i.AverageProgressPercent,
		&i.LatestReadAt,
	)
	return i, err
}

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT reading_progress.id, reading_progress.user_id, reading_progress.article_path, reading_progress.article_title,
       reading_progress.progress_percent, reading_progress.scroll_y, reading_progress.finished,
       reading_progress.last_read_at, reading_progress.created_at, reading_progress.updated_at
FROM reading_progress
JOIN content_items ON content_items.public_path = reading_progress.article_path
WHERE reading_progress.user_id = $1
  AND reading_progress.article_path = $2
  AND content_items.is_active
  AND content_items.content_type IN ('course_article', 'article', 'geektime_article', 'love_course_article')
`

type GetReadingProgressParams struct {
	UserID      int64
	ArticlePath string
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, getReadingProgress, arg.UserID, arg.ArticlePath)
	var i ReadingProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArticlePath,
		&i.ArticleTitle,
		&i.ProgressPercent,
		&i.ScrollY,
		&i.Finished,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourseArticlesWithProgress = `-- name: ListCourseArticlesWithProgress :many
SELECT content_items.public_path, content_items.title, course_articles.position,
       reading_progress.progress_percent, reading_progress.finished, reading_progress.last_read_at
FROM course_articles
JOIN content_items ON content_items.id = course_articles.content_item_id
LEFT JOIN reading_progress
  ON reading_progress.article_path = content_items.public_path
 AND reading_progress.user_id = $1
WHERE course_articles.course_id = $2
  AND course_articles.is_active
  AND content_items.is_active
ORDER BY course_articles.position
`

type ListCourseArticlesWithProgressParams struct {
	UserID   int64
	CourseID int64
}

type ListCourseArticlesWithProgressRow struct {
	PublicPath      string
	Title           string
	Position        int32
	ProgressPercent pgtype.Int4
	Finished        pgtype.Bool
	LastReadAt      pgtype.Timestamptz
}

func (q *Queries) ListCourseArticlesWithProgress(ctx context.Context, arg ListCourseArticlesWithProgressParams) ([]ListCourseArticlesWithProgressRow, error) {
	rows, err := q.db.Query(ctx, listCourseArticlesWithProgress, arg.UserID, arg.CourseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseArticlesWithProgressRow
	for rows.Next() {
		var i ListCourseArticlesWithProgressRow
		if err := rows.Scan(
			&i.PublicPath,
			&i.Title,
			&i.Position,
			&i.ProgressPercent,
			&i.Finished,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourseSummaries = `-- name: ListCourseSummaries :many
SELECT courses.public_path, courses.title, courses.article_count,
       COALESCE(user_course_progress.learned_article_count, 0)::int AS learned_article_count,
       COALESCE(user_course_progress.average_progress_percent, 0)::int AS average_progress_percent,
       user_course_progress.latest_read_at
FROM courses
LEFT JOIN user_course_progress
  ON user_course_progress.course_id = courses.id
 AND user_course_progress.user_id = $1
WHERE courses.is_active
ORDER BY courses.public_path
`

type ListCourseSummariesRow struct {
	PublicPath             string
	Title                  string
	ArticleCount           int32
	LearnedArticleCount    int32
	AverageProgressPercent int32
	LatestReadAt           pgtype.Timestamptz
}

func (q *Queries) ListCourseSummaries(ctx context.Context, userID int64) ([]ListCourseSummariesRow, error) {
	rows, err := q.db.Query(ctx, listCourseSummaries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCourseSummariesRow
	for rows.Next() {
		var i ListCourseSummariesRow
		if err := rows.Scan(
			&i.PublicPath,
			&i.Title,
			&i.ArticleCount,
			&i.LearnedArticleCount,
			&i.AverageProgressPercent,
			&i.LatestReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestReadingProgressByCoursePaths = `-- name: ListLatestReadingProgressByCoursePaths :many
SELECT courses.public_path AS course_path,
       reading_progress.id, reading_progress.user_id, reading_progress.article_path, reading_progress.article_title,
       reading_progress.progress_percent, reading_progress.scroll_y, reading_progress.finished,
       reading_progress.last_read_at, reading_progress.created_at, reading_progress.updated_at
FROM user_course_progress
JOIN courses ON courses.id = user_course_progress.course_id
JOIN content_items ON content_items.id = user_course_progress.latest_content_item_id
JOIN reading_progress
  ON reading_progress.user_id = user_course_progress.user_id
 AND reading_progress.article_path = content_items.public_path
WHERE user_course_progress.user_id = $1
  AND courses.public_path = ANY($2::text[])
  AND courses.is_active
  AND content_items.is_active
  AND content_items.content_type = 'course_article'
ORDER BY courses.public_path
`

type ListLatestReadingProgressByCoursePathsParams struct {
	UserID      int64
	CoursePaths []string
}

type ListLatestReadingProgressByCoursePathsRow struct {
	CoursePath      string
	ID              int64
	UserID          int64
	ArticlePath     string
	ArticleTitle    string
	ProgressPercent int32
	ScrollY         int32
	Finished        bool
	LastReadAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListLatestReadingProgressByCoursePaths(ctx context.Context, arg ListLatestReadingProgressByCoursePathsParams) ([]ListLatestReadingProgressByCoursePathsRow, error) {
	rows, err := q.db.Query(ctx, listLatestReadingProgressByCoursePaths, arg.UserID, arg.CoursePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestReadingProgressByCoursePathsRow
	for rows.Next() {
		var i ListLatestReadingProgressByCoursePathsRow
		if err := rows.Scan(
			&i.CoursePath,
			&i.ID,
			&i.UserID,
			&i.ArticlePath,
			&i.ArticleTitle,
			&i.ProgressPercent,
			&i.ScrollY,
			&i.Finished,
			&i.LastReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingProgressByArticlePaths = `-- name: ListReadingProgressByArticlePaths :many
SELECT reading_progress.id, reading_progress.user_id, reading_progress.article_path, reading_progress.article_title,
       reading_progress.progress_percent, reading_progress.scroll_y, reading_progress.finished,
       reading_progress.last_read_at, reading_progress.created_at, reading_progress.updated_at
FROM reading_progress
JOIN content_items ON content_items.public_path = reading_progress.article_path
WHERE reading_progress.user_id = $1
  AND reading_progress.article_path = ANY($2::text[])
  AND content_items.is_active
  AND content_items.content_type IN ('course_article', 'article', 'geektime_article', 'love_course_article')
`

type ListReadingProgressByArticlePathsParams struct {
	UserID       int64
	ArticlePaths []string
}

func (q *Queries) ListReadingProgressByArticlePaths(ctx context.Context, arg ListReadingProgressByArticlePathsParams) ([]ReadingProgress, error) {
	rows, err := q.db.Query(ctx, listReadingProgressByArticlePaths, arg.UserID, arg.ArticlePaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadingProgress
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ArticlePath,
			&i.ArticleTitle,
			&i.ProgressPercent,
			&i.ScrollY,
			&i.Finished,
			&i.LastReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentReadingProgress = `-- name: ListRecentReadingProgress :many
SELECT reading_progress.id, reading_progress.user_id, reading_progress.article_path, reading_progress.article_title,
       reading_progress.progress_percent, reading_progress.scroll_y, reading_progress.finished,
       reading_progress.last_read_at, reading_progress.created_at, reading_progress.updated_at
FROM reading_progress
JOIN content_items ON content_items.public_path = reading_progress.article_path
WHERE reading_progress.user_id = $1
  AND content_items.is_active
  AND content_items.content_type IN ('course_article', 'article', 'geektime_article', 'love_course_article')
ORDER BY reading_progress.last_read_at DESC
LIMIT $2
`

type ListRecentReadingProgressParams struct {
	UserID int64
	Limit  int32
}

func (q *Queries) ListRecentReadingProgress(ctx context.Context, arg ListRecentReadingProgressParams) ([]ReadingProgress, error) {
	rows, err := q.db.Query(ctx, listRecentReadingProgress, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReadingProgress
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ArticlePath,
			&i.ArticleTitle,
			&i.ProgressPercent,
			&i.ScrollY,
			&i.Finished,
			&i.LastReadAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rebuildCourseProgressForCourses = `-- name: RebuildCourseProgressForCourses :exec
DELETE FROM user_course_progress
WHERE course_id = ANY($1::bigint[])
`

func (q *Queries) RebuildCourseProgressForCourses(ctx context.Context, courseIds []int64) error {
	_, err := q.db.Exec(ctx, rebuildCourseProgressForCourses, courseIds)
	return err
}

const refreshUserCourseProgress = `-- name: RefreshUserCourseProgress :exec
INSERT INTO user_course_progress (
    user_id, course_id, learned_article_count, average_progress_percent, latest_content_item_id, latest_read_at, updated_at
)
SELECT
    $1,
    $2,
    COUNT(reading_progress.id)::int,
    COALESCE(ROUND(AVG(COALESCE(reading_progress.progress_percent, 0)))::int, 0),
    (
        SELECT course_articles.content_item_id
        FROM course_articles
        JOIN content_items ON content_items.id = course_articles.content_item_id
        JOIN reading_progress latest_progress
          ON latest_progress.article_path = content_items.public_path
         AND latest_progress.user_id = $1
        WHERE course_articles.course_id = $2
          AND course_articles.is_active
          AND content_items.is_active
        ORDER BY latest_progress.last_read_at DESC, latest_progress.id DESC
        LIMIT 1
    ),
    (
        SELECT latest_progress.last_read_at
        FROM course_articles
        JOIN content_items ON content_items.id = course_articles.content_item_id
        JOIN reading_progress latest_progress
          ON latest_progress.article_path = content_items.public_path
         AND latest_progress.user_id = $1
        WHERE course_articles.course_id = $2
          AND course_articles.is_active
          AND content_items.is_active
        ORDER BY latest_progress.last_read_at DESC, latest_progress.id DESC
        LIMIT 1
    ),
    NOW()
FROM course_articles
JOIN content_items ON content_items.id = course_articles.content_item_id
LEFT JOIN reading_progress
  ON reading_progress.article_path = content_items.public_path
 AND reading_progress.user_id = $1
WHERE course_articles.course_id = $2
  AND course_articles.is_active
  AND content_items.is_active
HAVING COUNT(reading_progress.id) > 0
ON CONFLICT (user_id, course_id)
DO UPDATE SET
    learned_article_count = EXCLUDED.learned_article_count,
    average_progress_percent = EXCLUDED.average_progress_percent,
    latest_content_item_id = EXCLUDED.latest_content_item_id,
    latest_read_at = EXCLUDED.latest_read_at,
    updated_at = NOW()
`

type RefreshUserCourseProgressParams struct {
	UserID   int64
	CourseID int64
}

func (q *Queries) RefreshUserCourseProgress(ctx context.Context, arg RefreshUserCourseProgressParams) error {
	_, err := q.db.Exec(ctx, refreshUserCourseProgress, arg.UserID, arg.CourseID)
	return err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :one
INSERT INTO reading_progress (user_id, article_path, article_title, progress_percent, scroll_y, finished, last_read_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
ON CONFLICT (user_id, article_path)
DO UPDATE SET
    article_title = EXCLUDED.article_title,
    progress_percent = GREATEST(reading_progress.progress_percent, EXCLUDED.progress_percent),
    scroll_y = GREATEST(reading_progress.scroll_y, EXCLUDED.scroll_y),
    finished = reading_progress.finished OR EXCLUDED.finished,
    last_read_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, article_path, article_title, progress_percent, scroll_y, finished, last_read_at, created_at, updated_at
`

type UpsertReadingProgressParams struct {
	UserID          int64
	ArticlePath     string
	ArticleTitle    string
	ProgressPercent int32
	ScrollY         int32
	Finished        bool
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRow(ctx, upsertReadingProgress,
		arg.UserID,
		arg.ArticlePath,
		arg.ArticleTitle,
		arg.ProgressPercent,
		arg.ScrollY,
		arg.Finished,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArticlePath,
		&i.ArticleTitle,
		&i.ProgressPercent,
		&i.ScrollY,
		&i.Finished,
		&i.LastReadAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
